config/routes.rb
Rails.application.routes.draw do
  get 'session/new'


  resources :users
  resources :recipients_users
  resources :histories
  resources :recipients
  resources :recipients do
    collection { post :import}
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  get	'login'    => 'session#new'
  post	'login'	   => 'session#create'
  get	'logout'   => 'session#destroy'
  get  'menu/:id'  => 'menu#index'        #idをindex(メニュー画面)に渡す
  post '/recipients/:id'  =>  'recipients#create'
  post '/recipients/:id'  =>  'recipients#update'
  root to: 'session#index'
  get 'menu/index' 
  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :recipients_users
    has_and_belongs_to_many :recipients
    validates :username,presence: true
    validates :password, presence: true
    validates :name, presence: true
    validates :busho, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    @search = User.search(params[:q])
    @users = @search.result
    @q = User.ransack(params[:q])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      respond_to do |format|
      if @user.save 
        format.html { redirect_to @user, notice: '登録されました' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|

      
      if params[:user][:password].blank?
        params[:user].delete("password")
      end
      

      if @user.update(user_params)
        format.html { redirect_to @user, notice: '保存されました' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: '削除されました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :name, :busho, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">


      <h2><%= pluralize(user.errors.count, "個のエラー") %> が発生しました:</h2>


      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ユーザ名 %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :パスワード %>
    <%= form.password_field :password %>
  </div>


  <div class="field">
    <%= form.label :氏名 %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :部署 %>
    <%= form.text_field :busho %>
  </div>

  <div class="field">
    <%= form.label :権限 %>
    <%= form.check_box :admin %>
  </div>
  <div class="actions">
    <%= form.submit:保存 %>
  </div>

  

  
<% end %>

app/views/users/edit.html.erb
<h1>ユーザ情報編集</h1>

<h4>＊パスワードを変更しないときは空欄のまま保存して下さい</h4>



<%= render 'form', user: @user %>

<%= link_to '詳細', @user %> |
<%= link_to 'ユーザ一覧へ', users_path  if @user.admin == true  %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>ユーザ一覧</h1>

<%= search_form_for @search do |f| %>
  <div class="form-group">
    <%= f.label :name_cont, "氏名を検索" %>
    <%= f.text_field :name_cont, class: "form-control" %>
  </div>

  　<%= f.label :権限 %>
  　<%= f.radio_button :admin_eq, '', {:checked => true} %>指定なし
    <%= f.radio_button :admin_eq, true %>あり
    <%= f.radio_button :admin_eq, false %>なし
    <br><br><%= link_to 'クリア', users_path %>
    
  <br><div class="actions"><%= f.submit "検索" %></div>


  <% end %>

<table>
  <thead>
  　<tr>
  　<th>氏名</th>
  　<th><%= sort_link(@q, :admin, "権限") %></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.admin ?  "あり" : "なし"%></td>

        <td><%= link_to '詳細', user %></td>
      </tr>
    <% end %>
  </tbody>
</table> 

<br>

<%= link_to '新規ユーザ登録', new_user_path %>
<%= link_to 'ログアウト', "/login" %>
<%# :backで前のページに戻るリンクが自動作成される %>

app/views/users/new.html.erb
<h1>新規ユーザ登録</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>ユーザ情報</h1>

<p>
  <strong>ユーザ名:</strong>
  <%= @user.username %>
</p>


<p>
  <strong>氏名:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>部署:</strong>
  <%= @user.busho %>
</p>

<p>
  <strong>権限:</strong>
   <%= @user.admin ?  "あり" : "なし"%>
</p>

<%= link_to '編集', edit_user_path(@user) %> |
<%= link_to 'ユーザ一覧へ', users_path   %>
<%= link_to 'ログアウト', login_path %>
<%= link_to '削除', @user, method: :delete, data: { confirm: '本当に削除していいですか?' } %>