config/routes.rb
Rails.application.routes.draw do
  get 'session/new'


  resources :users
  resources :recipients_users
  resources :histories
  resources :recipients
  resources :recipients do
    collection { post :import}
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  get	'login'    => 'session#new'
  post	'login'	   => 'session#create'
  get	'logout'   => 'session#destroy'
  get  'menu/:id'  => 'menu#index'        #idをindex(メニュー画面)に渡す
  post '/recipients/:id'  =>  'recipients#create'
  post '/recipients/:id'  =>  'recipients#update'
  root to: 'session#index'
  get 'menu/index' 
  
end

app/models/recipient.rb
class Recipient < ApplicationRecord
    has_many :histories
    has_and_belongs_to_many :users

    def self.import(file)
        CSV.foreach(file.path, headers: true, encoding: "utf-8") do |row|

            obj = new
            obj.attributes = row.to_hash.slice(*updatable_attributes)
            
            obj.save!
        end
    end
    def self.updatable_attributes
        ["name","shamei","sec_name1","sec_name2","position","post_code","address1","address2","dolor","honor","note"]
    end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_action :set_recipient, only: [:show, :edit, :update, :destroy ]

  # GET /recipients
  # GET /recipients.json
  def index
    @recipients = Recipient.all
    @users = User.all
    @recipientsusers = RecipientsUser.all

    @search = Recipient.search(params[:q])
    @recipient = @search.result
    respond_to do |format|
      format.html
      format.csv do
        recipients_csv
      end
    end
  end

  # GET /recipients/1
  # GET /recipients/1.json
  def show
    @histories = History.where(recipient_id:@recipient.id)
    @recipientsusers = RecipientsUser.where(recipient_id:@recipient.id)
  end
  # GET /recipients/new
  def new
    @recipient = Recipient.new
    @history = History.new
    @user = User.new
  end

  # GET /recipients/1/edit
  def edit
  end

  # POST /recipients
  # POST /recipients.json
  def create
    @recipient = Recipient.new(recipient_params)

    respond_to do |format|
      if @recipient.save
        format.html { redirect_to @recipient, notice: '送付先情報を作成しました。' }
        format.json { render :show, status: :created, location: @recipient }
      else
        format.html { render :new }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipients/1
  # PATCH/PUT /recipients/1.json
  def update
    respond_to do |format|
      if @recipient.update(recipient_params)
        format.html { redirect_to @recipient, notice: '送付先情報を更新しました。' }
        format.json { render :show, status: :ok, location: @recipient }
      else
        format.html { render :edit }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
      @history=History.new({"date"=>@recipient.updated_at,"user_id"=>1,"recipient_id"=>@recipient.id})
      @history.save
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.json
def destroy
  @recipient.destroy
  respond_to do |format|
    format.html { redirect_to recipients_url, notice: '送付先情報を削除しました。' }
    format.json { head :no_content }
  end
end
  
def import
  Recipient.import(params[:file])
  redirect_to "/recipients"
end

private
    # Use callbacks to share common setup or constraints between actions.
  def set_recipient
    @recipient = Recipient.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def recipient_params
    params.require(:recipient).permit(:name, :shamei, :sec_name1, :sec_name2, :position, :post_code, :address1, :address2, :dolor, :honor, :note)
  end

  def recipients_csv
    csv_date = CSV.generate(encoding: "SJIS") do |csv|
      csv_column_names = ["氏名","会社名","部署1","部署2","役職","郵便番号","住所1","住所2","喪中","備考"]
      csv << csv_column_names
      @recipients.each do |recipient|
        csv_column_values = [
          recipient.name,
          recipient.shamei,
          recipient.sec_name1,
          recipient.sec_name2,
          recipient.position,
          recipient.post_code,
          recipient.address1,
          recipient.address2,
          recipient.dolor,
          recipient.note,
        ]
        csv << csv_column_values
      end
    end
    send_data(csv_date,filename: "recipient.csv")
  end

end

app/views/recipients/_form.html.erb
<%= form_with(model: recipient, local: true) do |form| %>
  <% if recipient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipient.errors.count, "error") %> prohibited this recipient from being saved:</h2>

      <ul>
      <% recipient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :氏名 %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :会社名 %>
    <%= form.text_area :shamei %>
  </div>

  <div class="field">
    <%= form.label :部署1 %>
    <%= form.text_field :sec_name1 %>
  </div>

  <div class="field">
    <%= form.label :部署2 %>
    <%= form.text_field :sec_name2 %>
  </div>

  <div class="field">
    <%= form.label :役職名 %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :郵便番号 %>
    <%= form.number_field :post_code %>
  </div>

  <div class="field">
    <%= form.label :住所1 %>
    <%= form.text_area :address1 %>
  </div>

  <div class="field">
    <%= form.label :住所2 %>
    <%= form.text_area :address2 %>
  </div>

  <div class="field">
  </div>

  <div class="field">
    <%= form.label :喪中 %>
    <%= form.check_box :dolor%>
  </div>

  <div class="field">
    <%= form.label :備考 %>
    <%= form.text_area :note %>
  </div>

  <div class="actions">
    <%= form.submit:保存 %>
  </div>
<% end %>

app/views/recipients/edit.html.erb
<h1>送付先編集</h1>

<%= render 'form', recipient: @recipient %>

<%= link_to '表示', @recipient %> |
<%= link_to '戻る', @recipient %>

app/views/recipients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>送付先一覧表示</h1>

<%= search_form_for @search do |f| %>
  <div class="form-group">
    <%= f.label :name_cont,"氏名" %>
      <%= f.text_field :name_cont, class: "form-control" %>
    <%= f.label :shamei_cont,"会社名" %>
      <%= f.text_field :shamei_cont, class: "form-control" %>
    <%= f.label :address1_cont,"住所" %>
      <%= f.text_field :address1_cont, class: "form-control" %>
  </div>
  
  <%= f.label :喪中 %>
  　<%= f.radio_button :dolor_eq, '', {:checked => true} %>指定なし
    <%= f.radio_button :dolor_eq, true %>あり
    <%= f.radio_button :dolor_eq, false %>なし
  <br><br><%= link_to 'クリア', recipients_path %>

  <br><div class="action">
  <%= f.submit "検索" %></div>
  <% end %>

  
<br><%= link_to "エクスポート", recipients_path(format: :csv) %>

<%= form_tag import_recipients_path,multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "インポート" %>
<% end %>


<table>
  <thead>
    <tr>
    <th><%= sort_link(@search, :name, "氏名") %></th>
    <th><%= sort_link(@search, :shamei, "会社名") %></th>
    <th><%= sort_link(@search, :sec_name1, "部署1") %></th>
    <th><%= sort_link(@search, :sec_name2, "部署2") %></th>
    <th><%= sort_link(@search, :position, "役職") %></th>
    <th><%= sort_link(@search, :post_code, "郵便番号") %></th>
    <th><%= sort_link(@search, :address1, "住所1") %></th>
    <th><%= sort_link(@search, :address2, "住所2") %></th>
    <th><%= sort_link(@search, :honor, "担当者") %></th>
    <th><%= sort_link(@search, :dolor, "喪中") %></th>
    <th>備考</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipient.each do |recipient| %>
      <tr>
      <td><%= recipient.name %></td>
      <td><%= recipient.shamei %></td>
      <td><%= recipient.sec_name1 %></td>
      <td><%= recipient.sec_name2 %></td>
      <td><%= recipient.position %></td>
      <td><%= recipient.post_code %></td>
      <td><%= recipient.address1 %></td>
      <td><%= recipient.address2 %></td>
      <td>
      <% @recipientsusers = RecipientsUser.where(recipient_id:recipient.id) %>
      <% @recipientsusers.find_each do |uid|%>
      <% u = User.find(uid.user_id) %>
      <%= u.name %>
      <br>
      <% end %>
      </td>
      <td><%= recipient.dolor ?  "あり" : "なし"%></td>
      <td><%= recipient.note %></td>
      <td><%= link_to '詳細', recipient %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '送信先新規作成', new_recipient_path %>

app/views/recipients/new.html.erb
<h1>送付先新規作成</h1>

<%= render 'form', recipient: @recipient %>

<%= link_to '戻る', recipients_path %>

app/views/recipients/show.html.erb
<p id="notice"><%= notice %></p>

<h1>送付先情報</h1>

<p>
  <strong>氏名:</strong>
  <%= @recipient.name %>
</p>

<p>
  <strong>会社名:</strong>
  <%= @recipient.shamei %>
</p>

<p>
  <strong>部署1:</strong>
  <%= @recipient.sec_name1 %>
</p>

<p>
  <strong>部署2:</strong>
  <%= @recipient.sec_name2 %>
</p>

<p>
  <strong>役職名:</strong>
  <%= @recipient.position %>
</p>

<p>
  <strong>郵便番号:</strong>
  <%= @recipient.post_code %>
</p>

<p>
  <strong>住所1:</strong>
  <%= @recipient.address1 %>
</p>

<p>
  <strong>住所2:</strong>
  <%= @recipient.address2 %>
</p>

<p>
<strong>担当者:</strong>
  <% @recipientsusers.find_each do |uid|%>
  <% u = User.find(uid.user_id) %>
  <%= u.name %>
  <% end %>
</p>

<p>
  <strong>喪中:</strong>
  <%= @recipient.dolor %>
</p>

<p>
  <strong>敬称:</strong>
</p>

<p>
  <strong>備考:</strong>
  <%= @recipient.note %>
</p>


<table>
  <thead>
    <tr>  
      <th>変更履歴</th>
    </tr>
  </thead>
  
    <tr>
      <% @histories.find_each do |h| %>
      <tr><td><%= h.date %></td>
      <td><%= h.user_id %></td></tr>
      <br>
      <% end %>
  
    </tr>
</table>


<%= link_to '編集', edit_recipient_path(@recipient) %> |
<%= link_to '戻る', recipients_path %> |
<%= link_to '削除', @recipient, method: :delete, data: { confirm: '本当によろしいですか?' } %>