config/routes.rb
Rails.application.routes.draw do
  get 'session/new'


  resources :users
  resources :recipients_users
  resources :histories
  resources :recipients
  resources :recipients do
    collection { post :import}
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  get	'login'    => 'session#new'
  post	'login'	   => 'session#create'
  get	'logout'   => 'session#destroy'
  get  'menu/:id'  => 'menu#index'        #idをindex(メニュー画面)に渡す
  post '/recipients/:id'  =>  'recipients#create'
  post '/recipients/:id'  =>  'recipients#update'
  root to: 'session#index'
  get 'menu/index' 
  
end

app/models/recipients_user.rb
class RecipientsUser < ApplicationRecord
    belongs_to :recipient
    belongs_to :user
end

app/controllers/recipients_users_controller.rb
class RecipientsUsersController < ApplicationController
  before_action :set_recipients_user, only: [:show, :edit, :update, :destroy]

  # GET /recipients_users
  # GET /recipients_users.json
  def index
    @recipients_users = RecipientsUser.all
  end

  # GET /recipients_users/1
  # GET /recipients_users/1.json
  def show
  end

  # GET /recipients_users/new
  def new
    @recipients_user = RecipientsUser.new
  end

  # GET /recipients_users/1/edit
  def edit
  end

  # POST /recipients_users
  # POST /recipients_users.json
  def create
    @recipients_user = RecipientsUser.new(recipients_user_params)

    respond_to do |format|
      if @recipients_user.save
        format.html { redirect_to @recipients_user, notice: 'Recipients user was successfully created.' }
        format.json { render :show, status: :created, location: @recipients_user }
      else
        format.html { render :new }
        format.json { render json: @recipients_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipients_users/1
  # PATCH/PUT /recipients_users/1.json
  def update
    respond_to do |format|
      if @recipients_user.update(recipients_user_params)
        format.html { redirect_to @recipients_user, notice: 'Recipients user was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipients_user }
      else
        format.html { render :edit }
        format.json { render json: @recipients_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients_users/1
  # DELETE /recipients_users/1.json
  def destroy
    @recipients_user.destroy
    respond_to do |format|
      format.html { redirect_to recipients_users_url, notice: 'Recipients user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipients_user
      @recipients_user = RecipientsUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipients_user_params
      params.require(:recipients_user).permit(:recipient_id, :user_id)
    end
end

app/views/recipients_users/_form.html.erb
<%= form_with(model: recipients_user, local: true) do |form| %>
  <% if recipients_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipients_user.errors.count, "error") %> prohibited this recipients_user from being saved:</h2>

      <ul>
      <% recipients_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recipient_id %>
    <%= form.number_field :recipient_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipients_users/edit.html.erb
<h1>Editing Recipients User</h1>

<%= render 'form', recipients_user: @recipients_user %>

<%= link_to 'Show', @recipients_user %> |
<%= link_to 'Back', recipients_users_path %>

app/views/recipients_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipients Users</h1>

<table>
  <thead>
    <tr>
      <th>Recipient</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipients_users.each do |recipients_user| %>
      <tr>
        <td><%= recipients_user.recipient_id %></td>
        <td><%= recipients_user.user_id %></td>
        <td><%= link_to 'Show', recipients_user %></td>
        <td><%= link_to 'Edit', edit_recipients_user_path(recipients_user) %></td>
        <td><%= link_to 'Destroy', recipients_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipients User', new_recipients_user_path %>

app/views/recipients_users/new.html.erb
<h1>New Recipients User</h1>

<%= render 'form', recipients_user: @recipients_user %>

<%= link_to 'Back', recipients_users_path %>

app/views/recipients_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipient:</strong>
  <%= @recipients_user.recipient_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @recipients_user.user_id %>
</p>

<%= link_to 'Edit', edit_recipients_user_path(@recipients_user) %> |
<%= link_to 'Back', recipients_users_path %>